[versions]
jena = "4.10.0"
spring = "5.3.31"
joda-time = "2.13.0"
guava = "23.4-jre"
junit = "5.10.0"
assertj = "3.6.1"
vavr = "0.10.4"

[libraries]
spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
spring-web = { module = "org.springframework:spring-web", version.ref = "spring" }
joda-time = { module = "joda-time:joda-time", version.ref = "joda-time" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jena-arq = { module = "org.apache.jena:jena-arq", version.ref = "jena" }
jena-fuseki-main = { module = "org.apache.jena:jena-fuseki-main", version.ref = "jena" }
jena-rdfconnection = { module = "org.apache.jena:jena-rdfconnection", version.ref = "jena" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
vavr = { module = "io.vavr:vavr", version.ref = "vavr" }

[bundles]

[plugins]